version: '3.3'
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mapotempo/mapotempo-web:${MAPOTEMPO_VERSION:-latest}
    ports:
      - "8080:80" # HOST:CONTAINER, edit only HOST part
    volumes:
      - ./mapotempo.rb:/srv/app/config/initializers/mapotempo.rb
      - ./uploads:/srv/app/public/uploads
    links:
      - db
      - redis-cache
    env_file:
      - ./db.env
      - ./rails.env
    command: /bin/bash -c "chown www-data:www-data /srv/app/public/uploads && exec nginx -g 'daemon off;'"

  db:
    image: "postgres:9.6"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redis-cache:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    command: redis-server --save ""

  delayed-job:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mapotempo/mapotempo-web:${MAPOTEMPO_VERSION:-latest}
    ports: []
    volumes:
      - ./mapotempo.rb:/srv/app/config/initializers/mapotempo.rb
      - web-uploads:/srv/app/public/uploads
    links:
      - db
      - redis-cache
    env_file:
      - ./db.env
      - ./rails.env
    command: /bin/bash -c "chown www-data:www-data /srv/app/public/uploads && exec sudo -E -u www-data /usr/bin/bundle exec /srv/app/bin/delayed_job run -n 4"

volumes:
    web-uploads:
